icons_format = "{icon}"

[theme]
theme = "modern"

[theme.overrides]
# Example: redefine `idle` colors
idle_bg = "#393939"

[icons]
icons = "material-nf"

[[block]]
block = "music"

[[block]]
block = "custom"
command = "screen_recording.sh status"
interval = "once"
signal = 8
json = true
[[block.click]]
button = "left"
cmd = "screen_recording.sh toggle"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 5.0
alert = 5.0
format = " $icon /$available "

[[block]]
block = "load"

[[block]]
block = "net"

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(w:2) ($mem_avail_percents) "

[[block]]
block = "rofication"

[[block]]
block = "battery"
format = " $icon  $percentage {$time |} "
full_format = " $icon  $percentage {$time |} "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "weather"
format = " $icon {$temp}C "
autolocate = true
[block.service]
name = "metno"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
